#coding:utf8
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class SERVICE_ERROR:
  COMMON_ERROR_DATA_DUPLICATE = 1
  COMMON_ERROR_DATA_NOT_EXIST = 2
  COMMON_ERROR_STORAGE_FAIL = 3
  COMMON_ERROR_READ_ONLY = 4
  COMMON_ERROR_DATA_TOO_LARGE = 5

  _VALUES_TO_NAMES = {
    1: "COMMON_ERROR_DATA_DUPLICATE",
    2: "COMMON_ERROR_DATA_NOT_EXIST",
    3: "COMMON_ERROR_STORAGE_FAIL",
    4: "COMMON_ERROR_READ_ONLY",
    5: "COMMON_ERROR_DATA_TOO_LARGE",
  }

  _NAMES_TO_VALUES = {
    "COMMON_ERROR_DATA_DUPLICATE": 1,
    "COMMON_ERROR_DATA_NOT_EXIST": 2,
    "COMMON_ERROR_STORAGE_FAIL": 3,
    "COMMON_ERROR_READ_ONLY": 4,
    "COMMON_ERROR_DATA_TOO_LARGE": 5,
  }


class ServiceException(TException):
  """
  Attributes:
   - error: 错误id
   - msg: 错误描述
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'error', None, None, ), # 1
    (2, TType.STRING, 'msg', None, None, ), # 2
  )

  def __init__(self, error=None, msg=None,):
    self.error = error
    self.msg = msg

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.error = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.msg = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('ServiceException')
    if self.error is not None:
      oprot.writeFieldBegin('error', TType.I32, 1)
      oprot.writeI32(self.error)
      oprot.writeFieldEnd()
    if self.msg is not None:
      oprot.writeFieldBegin('msg', TType.STRING, 2)
      oprot.writeString(self.msg)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __str__(self):
    return repr(self)

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
